#!/usr/bin/env bash

if ! command -v packwiz 2>&1 >/dev/null
then
    echo "packwiz command not found, skipping packwiz refresh"
    exit 0
fi

git stash --keep-index --include-untracked --quiet
trap "git stash pop --quiet" EXIT

for package in */package
do
    pushd "$package"
    packwiz refresh
    git add {index,pack}.toml
    popd
done
