name = "the pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1b92e3027ad68e9c8a326c9a323ac57672b51aa482041187f8dddaeb811eb9b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"

[options]
acceptable-game-versions = ["1.21"]
