name = "the pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "721a408392b6f2226145471d2364643bad0e8bf8521754edaaba281654c9e3c7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"

[options]
acceptable-game-versions = ["1.21"]
