name = "the pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29e0274c9a77c155c6476a6763772ab4a1fea357c284d9eeb3a6c2f1c87ecdde"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
